### ISSUE TITLE
KeyError at /  'REMOTE_PORT'

### ISSUE THREAD

**Issue by nordbit** [jazzband/django-ddp#26]
```
/srv/py/python3/lib/python3.4/site-packages/dddp/views.py in get

 256.                           request.META['REMOTE_ADDR'], request.META['REMOTE_PORT'],

```

python==3.4, django==1.8.6

**Comment by tysonclugg** [comment]
@nordbit, can you please post the entire stack trace?

**Comment by tysonclugg** [comment]
@nordbit, the only way I can reproduce this error is when I use `manage.py runserver` instead of using `dddp` to start the web server.

Admittedly, the documentation is sub-standard but it does say that you should "Run your application using the `dddp` command" in the "Overview and getting started" section, and again in the "Example usage" section it is mentioned again.

Ticket https://github.com/django-ddp/django-ddp/issues/31 asks for better documentation, I'm closing this issue as invalid.  I'm happy for you to re-open it if you feel this hasn't been resolved.

**Comment by moaxey** [comment]
Thankyou

> PYTHONPATH=`pwd` DJANGO_SETTINGS_MODULE=appname.settings dddp
