### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [jazzband/django-ddp#29]
Hi please check the images as a result of attempt to install django-ddp
<img width="1280" alt="screen shot 2015-11-29 at 6 57 11 pm" src="https://cloud.githubusercontent.com/assets/9837087/11456676/38ec6a54-96cb-11e5-91ac-55e344615513.png">
<img width="1280" alt="screen shot 2015-11-29 at 6 57 19 pm" src="https://cloud.githubusercontent.com/assets/9837087/11456677/38ee5012-96cb-11e5-8c7b-b75978ec3370.png">
<img width="1280" alt="screen shot 2015-11-29 at 6 57 24 pm" src="https://cloud.githubusercontent.com/assets/9837087/11456679/38f3d7c6-96cb-11e5-87af-57a9a353fcce.png">
<img width="1280" alt="screen shot 2015-11-29 at 6 57 29 pm" src="https://cloud.githubusercontent.com/assets/9837087/11456678/38f1a06e-96cb-11e5-85a1-7c2b480ceceb.png">
<img width="1280" alt="screen shot 2015-11-29 at 6 57 33 pm" src="https://cloud.githubusercontent.com/assets/9837087/11456680/38f6682e-96cb-11e5-864e-4ca03485d6aa.png">
<img width="1280" alt="screen shot 2015-11-29 at 6 57 41 pm" src="https://cloud.githubusercontent.com/assets/9837087/11456681/38f994cc-96cb-11e5-9d7b-f0ada5be3973.png">
<img width="1280" alt="screen shot 2015-11-29 at 6 57 47 pm" src="https://cloud.githubusercontent.com/assets/9837087/11456682/39277d4c-96cb-11e5-8972-982efea1154e.png">

**Comment by tysonclugg** [comment]
Hi @Dean-Christian-Armada and thanks for the bug report.

The error message shown in red indicates to me an issue installing `gevent` on your system and is not an issue specific to `django-ddp`.  It looks similar to https://github.com/gevent/gevent/issues/690 but it's not clear as that bug report doesn't include the full stack trace.

My suggestion is you try again and submit the full console output to that ticket, but this time as text instead of screen captures (http://www.macworld.com/article/1059321/termtext.html).

I'll refrain from closing this issue as invalid until either:
1. It's confirmed another piece of software is responsible for the failure, or;
2. One week has elapsed with no further conversation on this issue.

Regards,
Tyson.

**Comment by Dean-Christian-Armada** [comment]
Ok thank you Tyson. I'll try everything you said
