### ISSUE TITLE
Mentoring available

### ISSUE THREAD

**Issue by noteworthyarcherfish** [jazzband/django-ddp#47]
Edit: Project not abandoned, mentoring available!

Hai,

This project looks abandoned?  I have real site using django-dddp

**Comment by codyparker** [comment]
I don't know if it's been abandoned. It could be that @tysonclugg has been busy on other projects. But he does have a production site using it, so I doubt it's completely abandoned.

**Comment by imsdigital** [comment]
I sure hope not.  It looks to me to be the PERFECT  answer for django developers wishing to transition to meteor.  I think he is missing a far wider audience with the project name, something like meteor-django would get more attention.

**Comment by codyparker** [comment]
I think you're right. I didn't find it until I was just about to give up and go straight meteor/mongo. I then stumbled across it mentioned in a blog. Getting to use Django's models and postgres is a big plus over straight meteor at this point, in my opinion....until _maybe_ when MDG adds postgres support directly into meteor, that is.

**Comment by imsdigital** [comment]
That is EXACTLY what happened to me.  In fact, we had started writing the glue (red code :-) taking records back and forwards between mongo and PostgreSQL when I stumbled across this project.

**Comment by codyparker** [comment]
Good timing then! That wouldn't have been fun to write or maintain. There is a [meteor-postgres ](https://github.com/meteor-stream/meteor-postgres) project, but it's been abandoned due to MDG announcing future postgres support. However, I may prefer django-ddp to even official support of postgres, with the ability to use Django's model system (and python!).

**Comment by imsdigital** [comment]
You and I are on the same page for sure.  Being able to use the django ORM is a huge plus for me, as is python.  I dipped my toe into node.js and ran back to python as fast as my legs would take me.

Same with Mongo and PostgreSQL.  The lack of structure seems like it would cause huge problems further down the road.

Steve

**Comment by dburles** [comment]
Hey guys, I can't comment on whether or not this project has been abandoned or not, though @codyparker is right that it's used in a production app. Keep an eye on Meteor's [Apollo Stack](https://github.com/apollostack/apollo). It's in the very early stages of development, but it aims to ultimately be a backend agnostic solution to providing a reactive data source to the client.

**Comment by codyparker** [comment]
Nice! Thanks for the heads up on that project, @dburles.

**Comment by tysonclugg** [comment]
Hi all. I'm not going to lie, I haven't had any time for Django DDP since I started with my new employer on early Feb 2016. That plus my laptop screen broke which isn't an issue at home or at work, but i can't work during my hour long commute on the train each morning/evening. Good news though, new laptop on order, and new employer wants real-time admin. Both of those points are really good for Django DDP moving forward. I'm still keen to mentor new people and spread the load, PM me if you're keen.

**Comment by tysonclugg** [comment]
So, I'm leaving this open until I get at least 1 more person willing to commit some time to the project... Leave a comment if you're interested.

**Comment by codyparker** [comment]
Hey @tysonclugg, I'm using django-ddp in a new project here at work. It's not where 100% of my time is spent right now, but I'm interested in contributing and helping when I can.

**Comment by tysonclugg** [comment]
I've moved Django DDP to Jazzband.  The project is somewhat legacy since it is likely that Django Channels will become part of Django core.
