### ISSUE TITLE
Django Channels

### ISSUE THREAD

**Issue by freakypie** [jazzband/django-ddp#50]
As [Django Channels](http://channels.readthedocs.io/en/latest/index.html) is [slated](http://channels.readthedocs.io/en/latest/inshort.html#what-version-of-django-does-it-work-with) to be a part of django in an upcoming release, would you consider adding support for it in django-ddp?

**Comment by tysonclugg** [comment]
I don't have plans to convert this project, since the differences between asyncio and gevent are substantial.  It is likely that the different django-ddp subsystems (pub-sub, async notifications, DDP API endpoints, etc) can be broken out into separate projects using Channels with much narrower scope.  I'm currently working with the author of Channels to see if it's possible to include pub-sub into channels itself.

**Comment by jpic** [comment]
Hi ! Has there been any follow up or is making a version of ddp that supports channel2 still a relevant / forward-compatible track to follow ?
